language: bash

services: 
  - docker

env:
  - TOMCAT_VER=8.5.35 JRE_VER=jre8  DIST=slim
  - TOMCAT_VER=8.5.35 JRE_VER=jre8  DIST=slim
  - TOMCAT_VER=9.0.13 JRE_VER=jre11 DIST=slim
  - TOMCAT_VER=8.5.35 JRE_VER=jre8  DIST=alpine
  - TOMCAT_VER=9.0.13 JRE_VER=jre8  DIST=alpine

before_script:
  - cd "magnolia-base/$DIST"
  - image="magnolia/magnolia-base:$TOMCAT_VER-$JRE_VER-$DIST"

script:
  - docker build --build-arg TOMCAT_VER  --build-arg JRE_VER --tag $image .
      
deploy:
  provider: script
  script: 
    - |
      (
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push $image
      )
  on:
    branch: master
# vim:set et ts=2 sw=2: