# Default values for magnolia.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/magnolia-sre/magnolia-docker/magnolia-docker
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  name: http
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    memory: 1000Mi
  requests:
    cpu: 500m
    memory: 1000Mi

nodeSelector: {}

tolerations: []

affinity: {}

liveness:
  httpGet:
    path: /.rest/status
    port: http
  timeoutSeconds: 4
  periodSeconds: 5
  failureThreshold: 3
  initialDelaySeconds: 90

readiness:
  httpGet:
    path: /.rest/status
    port: http
  timeoutSeconds: 4
  periodSeconds: 6
  failureThreshold: 3
  initialDelaySeconds: 90

# Replaced with liveness after successful startup
# Supported for 1.16 (alpha). Needs to be enabled per Feature Gates.
# https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#using-a-feature
# https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/deployment#startup_probe
# TODO: enable this on the cluster and tighten the liveness probe!
startupProbe:
#  httpGet:
#    path: /.rest/status
#    port: http
#  failureThreshold: 30
#  periodSeconds: 6
