apiVersion: v1
kind: Service
metadata:
  name: {{ include "magnolia.fullname" . }}
  labels:
    {{- include "magnolia.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "magnolia.selectorLabels" . | nindent 4 }}
